name: telkom
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.5
  google_maps_flutter: ^2.6.1
  flutter_polyline_points: ^2.0.0
  geocoding: ^3.0.0
  google_fonts: ^6.2.1
  iconsax: ^0.0.8
  flutter_native_splash: ^2.4.0





dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true



  assets:
    - assets/




#